version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: polls_db
      POSTGRES_USER: polls_user
      POSTGRES_PASSWORD: polls_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
